application: mnemonic-official
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /(css|js|images|fonts)/(.*)
  static_files: static/\1/\2
  upload: static/.*
  expiration: "1d"
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico
- url: (.*?)/robots\.txt
  static_files: robots.txt
  upload: robots\.txt
- url: /admin(/.*)?
  script: admin.app
  login: admin
- url: /.*
  script: main.app

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest
