application: mnemonic-official
version: 1
runtime: php
api_version: 1
threadsafe: yes

handlers:
- url: /(.*\.(html|css|js|gif|jpg|png|ico|fancybox))
  static_files: static/\1
  upload: static/.*
  expiration: "1d"

- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: .*
  script: main.php
