application: mnemonic-official
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /(.*\.(html|css|js|gif|jpg|png|ico))
  static_files: static/\1
  upload: static/.*
  expiration: "1d"

- url: /.*
  script: main.app

libraries:
- name: jinja2
  version: latest
